### ISSUE TITLE
Проблема с запуском сервера

### ISSUE THREAD

**Issue by ghost** [hilltty/hilltty-flags#15]
https://imgur.com/a/njpxU8K

Все флаги использовал ваши. (Только без больших страниц, потому что у меня виндовс 7)
OpenJDK 17.0.1
Paper 1.18.2 312

**Comment by GIGABAIT93** [comment]
У мене школо по створеню серверів?

ср, 27 квіт. 2022 р. о 14:54 F1rsi ***@***.***> пише:

**Comment by Anarchist-byte** [comment]
Вы забыли где-то перед **X** поставить **-**
