### ISSUE TITLE
UseBiasedLocking Is deprecated in Java 15

### ISSUE THREAD

**Issue by greysilly7** [hilltty/hilltty-flags#2]
When starting the server I get 
```
OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.
```

**Comment by hilltty** [comment]
hi, I know that when the server is turned on, such a message appears, but oddly enough, the function works more than correctly, so it can be safely ignored
