### ISSUE TITLE
Erros?

### ISSUE THREAD

**Issue by greysilly7** [hilltty/hilltty-flags#5]
OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.
Error occurred during initialization of VM
Option -XX:+UseShenandoahGC not supported

**Comment by hilltty** [comment]
Most likely you are using OracleJDK and it is not supported, try installing OpenJDK

**Comment by greysilly7** [comment]
I should mention I am using the docker image ``openjdk:18``, So I am using OpenJDK

**Comment by hilltty** [comment]
Oh, maybe the test build of OpenJDK 18 does not have all the necessary functions, I think if you go back to version 16 everything will be ok

**Comment by greysilly7** [comment]
Ok let me test, I will be right back

**Comment by greysilly7** [comment]
Ok I get this now, got rid of large Pages stuff cause I was lazy
```
Unrecognized VM option 'ShenandoahGCMode=iu'
Did you mean '(+/-)UseShenandoahGC'? Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
My JVM flags are 
```-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:-UseBiasedLocking -XX:+DisableExplicitGC -Dfile.encoding=UTF-8```

**Comment by hilltty** [comment]
Are you using Pterodactyl by any chance? I already write with a similar problem, and it seems like I decided to install AdoptOpenJDK to replace OpenJDK

**Comment by greysilly7** [comment]
No I am not using Pterodactyl found it a pain to install so I quit trying to install it

**Comment by greysilly7** [comment]
Weird thing is, that these flags work on all my other "openjdk:16" servers

**Comment by hilltty** [comment]
Can't you install the JDK with a regular command? For Ubuntu: `sudo apt install openjdk16-jre`

**Comment by greysilly7** [comment]
I lied sorry I use "adoptopenjdk/openjdk16:alpine-jre", let me try changing my docker image to that

Edit: Switching my image to AdoptOpenJDK fixed it, sorry for the trouble, and if you were curious I used a thing called pufferpanel because I have some friends I host for also and its easier for them

**Comment by hilltty** [comment]
No problem, thanks for using my flags :)
